# Generated by Django 2.0.5 on 2018-06-01 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_mgt', '0002_auto_20180601_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('C', 'Cutting'), ('P', 'Printing'), ('E', 'Extruder')], default='not specified', max_length=200, verbose_name='machine_type')),
                ('machine_number', models.CharField(max_length=10, verbose_name='machine_number')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('1', 'shift 1'), ('2', 'shift 2'), ('3', 'shift 3')], default='not specified', max_length=200, verbose_name='shift')),
                ('working_date', models.DateField(verbose_name='working_date')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.Machine')),
                ('workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Employee')),
            ],
        ),
    ]
