# Generated by Django 2.0.6 on 2018-10-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_mgt', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('datetime_in', models.DateTimeField(verbose_name='datetime_in')),
                ('datetime_out', models.DateTimeField(verbose_name='datetime_out')),
                ('line', models.CharField(choices=[('Line 1', 'Line 1'), ('Line 2', 'Line 2'), ('Line 3', 'Line 3')], default='1', max_length=200, verbose_name='line')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantity')),
                ('output_kilos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='output_kilos')),
                ('number_rolls', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='number_rolls')),
                ('exit_scrap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='exit_scrap')),
                ('cutting_scrap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='cutting_scrap')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='ExtruderSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('shift', models.CharField(choices=[('Shift 1', 'shift 1'), ('Shift 2', 'shift 2'), ('Shift 3', 'shift 3')], default='not specified', max_length=200, verbose_name='shift')),
                ('datetime_in', models.DateTimeField(verbose_name='datetime_in')),
                ('datetime_out', models.DateTimeField(verbose_name='datetime_out')),
                ('weight_rolls', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='weight_rolls')),
                ('core_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='core_weight')),
                ('output_kilos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='output_kilos')),
                ('number_rolls', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='number_rolls')),
                ('starting_scrap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='starting_scrap')),
                ('extruder_scrap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='extruder_scrap')),
                ('balance', models.IntegerField(verbose_name='balance')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rush_order', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('On Queue', 'On Queue'), ('Under Cutting', 'Under Cutting'), ('Under Extrusion', 'Under Extrusion'), ('Under Printing', 'Under Printing'), ('Under Packaging', 'Under Packaging'), ('Ready for delivery', 'Ready for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=200, verbose_name='status')),
                ('remarks', models.CharField(blank=True, default='', max_length=250, verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('Cutting', 'Cutting'), ('Printing', 'Printing'), ('Extruder', 'Extruder')], default='not specified', max_length=200, verbose_name='machine_type')),
                ('machine_number', models.CharField(max_length=10, verbose_name='machine_number')),
            ],
        ),
        migrations.CreateModel(
            name='MachineSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_task', models.CharField(blank=True, default='Extruder', max_length=200, verbose_name='job_task')),
                ('duration', models.DurationField()),
                ('job_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_mgt.JobOrder')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0, verbose_name='state')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('datetime_in', models.DateTimeField(verbose_name='datetime_in')),
                ('datetime_out', models.DateTimeField(verbose_name='datetime_out')),
                ('number_rolls', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='number_rolls')),
                ('exit_scrap', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='exit_scrap')),
                ('printing_scrap', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='printing_scrap')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='remarks')),
                ('job_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_mgt.JobOrder')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.Machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Employee')),
            ],
        ),
    ]
