# Generated by Django 2.0.6 on 2018-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingschedule',
            name='shift',
            field=models.CharField(choices=[('Shift 1', 'shift 1'), ('Shift 2', 'shift 2'), ('Shift 3', 'shift 3')], default='not specified', max_length=200, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='shift',
            field=models.CharField(choices=[('Shift 1', 'shift 1'), ('Shift 2', 'shift 2'), ('Shift 3', 'shift 3')], default='not specified', max_length=200, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('Cutting', 'Cutting'), ('Printing', 'Printing'), ('Extruder', 'Extruder')], default='not specified', max_length=200, verbose_name='machine_type'),
        ),
        migrations.AlterField(
            model_name='machineschedule',
            name='shift',
            field=models.CharField(choices=[('Shift 1', 'shift 1'), ('Shift 2', 'shift 2'), ('Shift 3', 'shift 3')], default='not specified', max_length=200, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='shift',
            field=models.CharField(choices=[('Shift 1', 'shift 1'), ('Shift 2', 'shift 2'), ('Shift 3', 'shift 3')], default='not specified', max_length=200, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='workerschedule',
            name='shift',
            field=models.CharField(choices=[('Shift 1', 'shift 1'), ('Shift 2', 'shift 2'), ('Shift 3', 'shift 3')], default='not specified', max_length=200, verbose_name='shift'),
        ),
    ]
