# Generated by Django 2.1.2 on 2018-11-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingschedule',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.JobOrder'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Machine'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.JobOrder'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Machine'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
        migrations.AlterField(
            model_name='laminatingschedule',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.JobOrder'),
        ),
        migrations.AlterField(
            model_name='laminatingschedule',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Machine'),
        ),
        migrations.AlterField(
            model_name='laminatingschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.JobOrder'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Machine'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
    ]
