# Generated by Django 2.0.5 on 2018-06-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0005_auto_20180603_1451'),
        ('production_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, default='none', max_length=200, verbose_name='article')),
                ('vat', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, verbose_name='vat')),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.ClientPO')),
            ],
        ),
    ]
