# Generated by Django 2.0.6 on 2018-07-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_mgt', '0002_auto_20180703_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingschedule',
            name='client_po',
        ),
        migrations.RemoveField(
            model_name='extruderschedule',
            name='client_po',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='cutting_schedule',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='extruder_schedule',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='printing_schedule',
        ),
        migrations.RemoveField(
            model_name='printingschedule',
            name='client_po',
        ),
        migrations.AddField(
            model_name='cuttingschedule',
            name='job_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_mgt.JobOrder'),
        ),
        migrations.AddField(
            model_name='extruderschedule',
            name='job_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_mgt.JobOrder'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='rush_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printingschedule',
            name='job_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_mgt.JobOrder'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='status',
            field=models.CharField(choices=[('On Queue', 'On Queue'), ('Under Cutting', 'Cutting'), ('Under Extrusion', 'Under Extrusion'), ('Under Printing', 'Under Printing'), ('Under Packaging', 'Under Packaging'), ('Ready for delivery', 'Ready for delivery'), ('Delivered', 'Delivered')], default='', max_length=200, verbose_name='status'),
        ),
    ]
