# Generated by Django 2.1.2 on 2018-11-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20181111_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('Cutting', 'Cutting'), ('Printing', 'Printing'), ('Extruder', 'Extruder'), ('Laminating', 'Laminating')], default='not specified', max_length=200, verbose_name='machine_type'),
        ),
    ]
