# Generated by Django 2.1a1 on 2018-06-18 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0003_auto_20180618_1355'),
        ('production_mgt', '0003_auto_20180618_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('remarks', models.CharField(max_length=250, verbose_name='remarks')),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.ClientPO')),
            ],
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='line',
            field=models.CharField(default='1', max_length=200, verbose_name='line'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.WorkerSchedule'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.WorkerSchedule'),
        ),
        migrations.AlterField(
            model_name='machineschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.WorkerSchedule'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.WorkerSchedule'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='repeat_order',
            field=models.BooleanField(default=True, verbose_name='repeat_order'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='cutting_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.CuttingSchedule'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='extruder_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.ExtruderSchedule'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='printing_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.PrintingSchedule'),
        ),
    ]
