# Generated by Django 2.1.2 on 2018-11-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20181111_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborder',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='is_laminate',
        ),
        migrations.AlterField(
            model_name='joborder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client'),
        ),
    ]
