# Generated by Django 2.0.6 on 2018-07-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_mgt', '0003_auto_20180704_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('On Queue', 'On Queue'), ('Under Cutting', 'Cutting'), ('Under Extrusion', 'Under Extrusion'), ('Under Printing', 'Under Printing'), ('Under Packaging', 'Under Packaging'), ('Ready for delivery', 'Ready for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=200, verbose_name='status'),
        ),
    ]
