# Generated by Django 2.1.2 on 2018-11-11 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20181111_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='date_issued',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_issued'),
            preserve_default=False,
        ),
    ]
