# Generated by Django 2.0.6 on 2018-07-23 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production_mgt', '0004_auto_20180704_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0, verbose_name='state')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_mgt.Machine')),
            ],
        ),
        migrations.RemoveField(
            model_name='machineschedule',
            name='client_po',
        ),
        migrations.RemoveField(
            model_name='machineschedule',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='machineschedule',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='workerschedule',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='workerschedule',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='cuttingschedule',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='cuttingschedule',
            name='print_name',
        ),
        migrations.RemoveField(
            model_name='cuttingschedule',
            name='sealing',
        ),
        migrations.RemoveField(
            model_name='cuttingschedule',
            name='starting_scrap',
        ),
        migrations.RemoveField(
            model_name='extruderschedule',
            name='material',
        ),
        migrations.RemoveField(
            model_name='extruderschedule',
            name='stock_kind',
        ),
        migrations.RemoveField(
            model_name='extruderschedule',
            name='treating',
        ),
        migrations.RemoveField(
            model_name='printingschedule',
            name='output_kilos',
        ),
        migrations.RemoveField(
            model_name='printingschedule',
            name='repeat_order',
        ),
        migrations.RemoveField(
            model_name='printingschedule',
            name='starting_scrap',
        ),
        migrations.AddField(
            model_name='cuttingschedule',
            name='day',
            field=models.CharField(choices=[('a.m.', 'a.m.'), ('p.m.', 'p.m.')], default='a.m.', max_length=200, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='cuttingschedule',
            name='exit_scrap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='exit_scrap'),
        ),
        migrations.AddField(
            model_name='extruderschedule',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='extruderschedule',
            name='day',
            field=models.CharField(choices=[('a.m.', 'a.m.'), ('p.m.', 'p.m.')], default='a.m.', max_length=200, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='printingschedule',
            name='day',
            field=models.CharField(choices=[('a.m.', 'a.m.'), ('p.m.', 'p.m.')], default='a.m.', max_length=200, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='printingschedule',
            name='exit_scrap',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=12, verbose_name='exit_scrap'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='cutting_scrap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='cutting_scrap'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='line',
            field=models.CharField(choices=[('Line 1', 'Line 1'), ('Line 2', 'Line 2'), ('Line 3', 'Line 3')], default='1', max_length=200, verbose_name='line'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='number_rolls',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='number_rolls'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Employee'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='output_kilos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='output_kilos'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='cuttingschedule',
            name='time_in',
            field=models.TimeField(blank=True, verbose_name='time_in'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='core_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='core_weight'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='extruder_scrap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='extruder_scrap'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='job_order',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='production_mgt.JobOrder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='net_weight'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='number_rolls',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='number_rolls'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Employee'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='output_kilos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='output_kilos'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='starting_scrap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='starting_scrap'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='time_in',
            field=models.TimeField(blank=True, verbose_name='time_in'),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='weight_rolls',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='weight_rolls'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='number_rolls',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='number_rolls'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Employee'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='printing_scrap',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='printing_scrap'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='time_in',
            field=models.TimeField(blank=True, verbose_name='time_in'),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='time_out',
            field=models.TimeField(auto_now_add=True, verbose_name='time_out'),
        ),
        migrations.DeleteModel(
            name='MachineSchedule',
        ),
        migrations.DeleteModel(
            name='WorkerSchedule',
        ),
    ]
