# Generated by Django 2.1.2 on 2018-11-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_joborder_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_issued'),
        ),
    ]
