# Generated by Django 2.0.6 on 2018-07-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_mgt', '0005_auto_20180723_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinestate',
            name='machine',
        ),
        migrations.DeleteModel(
            name='MachineState',
        ),
    ]
