# Generated by Django 2.1.2 on 2018-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20181111_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='date_issued',
            field=models.DateField(auto_now_add=True, verbose_name='date_issued'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='date_required',
            field=models.DateField(),
        ),
    ]
