# Generated by Django 2.1.2 on 2018-11-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20181112_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingschedule',
            name='shift',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extruderschedule',
            name='shift',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laminatingschedule',
            name='shift',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printingschedule',
            name='shift',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
