# Generated by Django 2.1.2 on 2018-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20181113_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingschedule',
            name='final',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extruderschedule',
            name='final',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laminatingschedule',
            name='final',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printingschedule',
            name='final',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
