# Generated by Django 2.0.6 on 2018-07-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_mgt', '0009_auto_20180723_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineschedule',
            name='operator',
        ),
    ]
