# Generated by Django 2.1.2 on 2018-11-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20181116_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingschedule',
            name='core_weight',
        ),
        migrations.RemoveField(
            model_name='cuttingschedule',
            name='weight_rolls',
        ),
    ]
