# Generated by Django 2.0.5 on 2018-05-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200, verbose_name='contact_name')),
                ('company', models.CharField(max_length=200, verbose_name='company')),
                ('accounts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Account')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Address')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_numbers', models.CharField(max_length=200, verbose_name='contact_numbers')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.CharField(max_length=200, verbose_name='emails')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last_name')),
                ('middle_initial', models.CharField(max_length=5, verbose_name='middle_initial')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('position', models.CharField(choices=[('GM', 'General Manager'), ('SC', 'Sales Coordinator'), ('SA', 'Sales Agent'), ('CC', 'Credits and Collection'), ('SV', 'Supervisor'), ('LL', 'Line Leader'), ('PM', 'Production Manager')], default='not specified', max_length=200, verbose_name='position')),
                ('accounts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Account')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Address')),
                ('contact_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.ContactNumber')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Email')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='contact_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.ContactNumber'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Email'),
        ),
    ]
