# Generated by Django 2.1a1 on 2018-06-25 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='not_specified', max_length=200, verbose_name='first_name')),
                ('last_name', models.CharField(default='not_specified', max_length=200, verbose_name='last_name')),
                ('company', models.CharField(max_length=200, verbose_name='company')),
                ('tin', models.CharField(blank=True, max_length=200, verbose_name='tin')),
                ('accounts', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Address')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_numbers', models.CharField(max_length=200, verbose_name='contact_numbers')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.CharField(max_length=200, verbose_name='emails')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=200, verbose_name='last_name')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('sss', models.CharField(blank=True, max_length=200, verbose_name='sss')),
                ('philhealth', models.CharField(blank=True, max_length=200, verbose_name='philhealth')),
                ('pagibig', models.CharField(blank=True, max_length=200, verbose_name='pagibig')),
                ('tin', models.CharField(blank=True, max_length=200, verbose_name='tin')),
                ('position', models.CharField(choices=[('GM', 'General Manager'), ('SC', 'Sales Coordinator'), ('SA', 'Sales Agent'), ('CC', 'Credits and Collection Personnel'), ('SV', 'Supervisor'), ('LL', 'Line Leader'), ('PM', 'Production Manager'), ('C', 'Cutting'), ('P', 'Printing'), ('E', 'Extruder'), ('D', 'Delivery'), ('W', 'Warehouse'), ('U', 'Utility'), ('M', 'Maintenance')], default='not specified', max_length=200, verbose_name='position')),
                ('accounts', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Address')),
                ('contact_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.ContactNumber')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Email')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='contact_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.ContactNumber'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='sales_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Employee'),
        ),
    ]
