# Generated by Django 2.0.6 on 2018-07-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='emails',
            field=models.EmailField(max_length=200, verbose_name='emails'),
        ),
    ]
