# Generated by Django 2.1a1 on 2018-06-18 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sales_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Employee'),
        ),
    ]
