# Generated by Django 2.0.5 on 2018-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0002_auto_20180601_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tin',
            field=models.CharField(blank=True, max_length=200, verbose_name='tin'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GM', 'General Manager'), ('SC', 'Sales Coordinator'), ('SA', 'Sales Agent'), ('CC', 'Credits and Collection Personnel'), ('SV', 'Supervisor'), ('LL', 'Line Leader'), ('PM', 'Production Manager'), ('C', 'Cutting'), ('P', 'Printing'), ('E', 'Extruder'), ('D', 'Delivery'), ('W', 'Warehouse'), ('U', 'Utility'), ('M', 'Maintenance'), ('PM', 'Production Manager')], default='not specified', max_length=200, verbose_name='position'),
        ),
    ]
