# Generated by Django 2.0.6 on 2018-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0002_auto_20180703_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=200, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=200, verbose_name='last_name'),
        ),
    ]
