# Generated by Django 2.0.6 on 2018-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0003_auto_20180703_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('General Manager', 'General Manager'), ('Sales Coordinator', 'Sales Coordinator'), ('Sales Agent', 'Sales Agent'), ('Credits and Collection Personnel', 'Credits and Collection Personnel'), ('Supervisor', 'Supervisor'), ('Line Leader', 'Line Leader'), ('Production Manager', 'Production Manager'), ('Cutting', 'Cutting'), ('Printing', 'Printing'), ('Extruder', 'Extruder'), ('Delivery', 'Delivery'), ('Warehouse', 'Warehouse'), ('Utility', 'Utility'), ('Maintenance', 'Maintenance')], default='not specified', max_length=200, verbose_name='position'),
        ),
    ]
