# Generated by Django 2.1a1 on 2018-06-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0005_auto_20180605_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GM', 'General Manager'), ('SC', 'Sales Coordinator'), ('SA', 'Sales Agent'), ('CC', 'Credits and Collection Personnel'), ('SV', 'Supervisor'), ('LL', 'Line Leader'), ('PM', 'Production Manager'), ('C', 'Cutting'), ('P', 'Printing'), ('E', 'Extruder'), ('D', 'Delivery'), ('W', 'Warehouse'), ('U', 'Utility'), ('M', 'Maintenance')], default='not specified', max_length=200, verbose_name='position'),
        ),
    ]
