# Generated by Django 2.1.2 on 2018-12-04 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, choices=[('Raw Materials', 'Raw Materials'), ('Machine Parts', 'Machine Parts'), ('Ink', 'Ink'), ('Cylinder', 'Cylinder'), ('Others', 'Others')], default='Not specified', max_length=200, null=True, verbose_name='item_type')),
                ('rm_type', models.CharField(blank=True, choices=[('--', '----------------'), ('LDPE', 'Low-density polyethylene'), ('LLDPE', 'Linear low-density polyethylene'), ('HDPE', 'High-density polyethylene'), ('PP', 'Polypropylene'), ('PET', 'Polyethylene terephthalate'), ('Pelletized PE', 'Pelletized polyethylene '), ('Pelletized HD', 'Pelletized high-density polyethylene')], default='Not specified', max_length=200, null=True, verbose_name='rm_type')),
                ('item', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Supplier')),
            ],
            options={
                'db_table': 'inventory_mgt_inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_count', models.IntegerField(blank=True, null=True)),
                ('new_count', models.IntegerField(blank=True, null=True)),
                ('date_counted', models.DateField(blank=True, null=True)),
                ('count_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
            options={
                'db_table': 'inventory_mgt_inventorycount',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_issued', models.DateTimeField(auto_now_add=True)),
                ('shift', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('Retrieved', 'Retrieved'), ('Pending', 'Pending')], default='Pending', max_length=200, null=True)),
                ('client_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ClientItem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
            options={
                'db_table': 'inventory_mgt_materialrequisition',
            },
        ),
        migrations.CreateModel(
            name='SupplierPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Supplier')),
            ],
            options={
                'db_table': 'inventory_mgt_supplierpo',
            },
        ),
        migrations.CreateModel(
            name='SupplierPOItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('total_price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
                ('supplier_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.SupplierPO')),
            ],
            options={
                'db_table': 'inventory_mgt_supplierpoitems',
            },
        ),
    ]
