# Generated by Django 2.0.6 on 2018-07-03 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplieritems',
            options={'verbose_name_plural': 'Supplier items'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.AddField(
            model_name='inventorycountasof',
            name='old_count',
            field=models.IntegerField(default=0, verbose_name='old_count'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='date_issued',
            field=models.DateField(default=datetime.date(2018, 7, 3), verbose_name='date_issued'),
        ),
        migrations.AlterField(
            model_name='supplieritems',
            name='item_type',
            field=models.CharField(choices=[('RM', 'Raw Materials'), ('MP', 'Machine Parts'), ('INK', 'Ink'), ('OT', 'Others')], default='not specified', max_length=200, verbose_name='item_type'),
        ),
        migrations.AlterField(
            model_name='supplieritems',
            name='supplier',
            field=models.CharField(max_length=200, verbose_name='supplier'),
        ),
    ]
