# Generated by Django 2.0.5 on 2018-05-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='item_name')),
                ('item_type', models.CharField(choices=[('RM', 'Raw Materials'), ('MP', 'Machine Parts'), ('INK', 'Ink')], default='not specified', max_length=200, verbose_name='item_type')),
                ('price', models.IntegerField(verbose_name='price')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_mgt.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('delivery_date', models.DateField(verbose_name='delivery_date')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_mgt.Supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='brand',
        ),
        migrations.AddField(
            model_name='inventory',
            name='rm_name',
            field=models.CharField(default='not specified', max_length=200, verbose_name='rm_name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rm_type',
            field=models.CharField(choices=[('LDPE', 'Low-density polyethylene'), ('LLDPE', 'Linear low-density polyethylene'), ('HDPE', 'High-density polyethylene'), ('PP', 'Polypropylene'), ('PET', 'Polyethylene terephthalate')], default='not specified', max_length=200, verbose_name='rm_type'),
        ),
    ]
