# Generated by Django 2.0.5 on 2018-06-01 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0002_auto_20180601_1028'),
        ('inventory_mgt', '0002_auto_20180531_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPOTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieved', models.BooleanField(default=False, verbose_name='retrieved')),
                ('date_retrieved', models.DateField(blank=True, default='not yet retrieved', verbose_name='date_retrieved')),
                ('supplier_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_mgt.SupplierPO')),
            ],
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='placed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Employee'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='shift',
            field=models.CharField(choices=[('1', 'shift 1'), ('2', 'shift 2'), ('3', 'shift 3')], default='not specified', max_length=200, verbose_name='shift'),
        ),
    ]
