# Generated by Django 2.1.2 on 2018-11-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181111_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequisition',
            name='datetime_issued',
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='shift',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rm_type',
            field=models.CharField(blank=True, choices=[('--', '----------------'), ('LDPE', 'Low-density polyethylene'), ('LLDPE', 'Linear low-density polyethylene'), ('HDPE', 'High-density polyethylene'), ('PP', 'Polypropylene'), ('PET', 'Polyethylene terephthalate'), ('Pelletized PE', 'Pelletized polyethylene '), ('Pelletized HD', 'Pelletized high-density polyethylene')], default='Not specified', max_length=200, null=True, verbose_name='rm_type'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory'),
        ),
    ]
