# Generated by Django 2.0.6 on 2018-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgt', '0002_auto_20180703_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequisition',
            name='shift',
            field=models.CharField(choices=[('Shift 1', 'shift 1'), ('Shift 2', 'shift 2'), ('Shift 3', 'shift 3')], default='not specified', max_length=200, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='supplieritems',
            name='item_type',
            field=models.CharField(choices=[('Raw Materials', 'Raw Materials'), ('Machine Parts', 'Machine Parts'), ('Ink', 'Ink'), ('Others', 'Others')], default='not specified', max_length=200, verbose_name='item_type'),
        ),
    ]
