# Generated by Django 2.1.2 on 2018-11-13 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181113_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequisition',
            name='datetime_issued',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
