# Generated by Django 2.0.6 on 2018-07-14 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0029_auto_20180714_2252'),
        ('inventory_mgt', '0004_auto_20180704_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPOItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('total_price', models.IntegerField(verbose_name='total_price')),
            ],
            options={
                'verbose_name_plural': 'Supplier po items',
            },
        ),
        migrations.RemoveField(
            model_name='currentrminproduction',
            name='raw_material',
        ),
        migrations.DeleteModel(
            name='SupplierItems',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='rm_name',
        ),
        migrations.RemoveField(
            model_name='supplierpo',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(default=1, max_length=200, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(default='not specified', max_length=200, verbose_name='item_name'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('Raw Materials', 'Raw Materials'), ('Machine Parts', 'Machine Parts'), ('Ink', 'Ink'), ('Others', 'Others')], default='not specified', max_length=200, verbose_name='item_type'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.Supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='date_issued',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_issued'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierpo',
            name='total_amount',
            field=models.IntegerField(default=1, verbose_name='total_amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rm_type',
            field=models.CharField(blank=True, choices=[('--', '----------------'), ('LDPE', 'Low-density polyethylene'), ('LLDPE', 'Linear low-density polyethylene'), ('HDPE', 'High-density polyethylene'), ('PP', 'Polypropylene'), ('PET', 'Polyethylene terephthalate')], default='not specified', max_length=200, null=True, verbose_name='rm_type'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='date_issued',
            field=models.DateField(auto_now_add=True, verbose_name='date_issued'),
        ),
        migrations.DeleteModel(
            name='CurrentRMinProduction',
        ),
        migrations.AddField(
            model_name='supplierpoitems',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_mgt.Inventory'),
        ),
        migrations.AddField(
            model_name='supplierpoitems',
            name='supplier_po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_mgt.SupplierPO'),
        ),
    ]
