# Generated by Django 2.1.2 on 2018-11-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_materialrequisition_datetime_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='count_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
