# Generated by Django 2.1.2 on 2018-11-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181111_1923'),
        ('inventory', '0005_inventory_count_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_count', models.IntegerField(blank=True, null=True)),
                ('new_count', models.IntegerField(blank=True, null=True)),
                ('date_counted', models.DateField(blank=True, null=True)),
                ('count_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='count_person',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date_counted',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='new_count',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='old_count',
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory'),
        ),
    ]
