# Generated by Django 2.0.6 on 2018-07-18 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0037_auto_20180718_1010'),
        ('inventory_mgt', '0006_auto_20180717_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRawMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='price')),
                ('rm_type', models.CharField(blank=True, choices=[('--', '----------------'), ('LDPE', 'Low-density polyethylene'), ('LLDPE', 'Linear low-density polyethylene'), ('HDPE', 'High-density polyethylene'), ('PP', 'Polypropylene'), ('PET', 'Polyethylene terephthalate')], default='not specified', max_length=200, null=True, verbose_name='rm_type')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.Supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
    ]
