# Generated by Django 2.1.2 on 2018-11-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20181116_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Raw Materials', 'Raw Materials'), ('Machine Parts', 'Machine Parts'), ('Ink', 'Ink'), ('Cylinder', 'Cylinder'), ('Others', 'Others')], default='Not specified', max_length=200, null=True, verbose_name='item_type'),
        ),
    ]
