# Generated by Django 2.1.2 on 2018-11-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20181120_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequisition',
            name='shift',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
