# Generated by Django 2.1.2 on 2018-11-21 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20181120_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='date_counted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
