# Generated by Django 2.1a1 on 2018-06-25 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCreditStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_status', models.BooleanField(default=True, verbose_name='credit_status')),
                ('outstanding_balance', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='outstanding_balance')),
                ('total_paid', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='total_paid')),
                ('date_due', models.DateField(auto_now_add=True, verbose_name='date_due')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client')),
            ],
            options={
                'verbose_name_plural': 'Client credit status',
            },
        ),
        migrations.CreateModel(
            name='ClientItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laminate', models.BooleanField(default=False, verbose_name='laminate')),
                ('width', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='width')),
                ('length', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='length')),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('O', 'Orange'), ('G', 'Green'), ('V', 'Violet'), ('Blk', 'Black'), ('Wht', 'White'), ('P', 'Plain')], max_length=200, verbose_name='color')),
                ('gusset', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='gusset')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('item_price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='date_issued')),
                ('date_required', models.DateTimeField(auto_now_add=True, verbose_name='date_required')),
                ('note', models.CharField(default='', max_length=200, verbose_name='note')),
                ('terms', models.CharField(max_length=250, verbose_name='terms')),
                ('other_info', models.CharField(max_length=250, verbose_name='other_info')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='total_amount')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=200, verbose_name='products')),
                ('prod_price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='prod_price')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True, verbose_name='date_issued')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, verbose_name='total_amount')),
                ('discount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, verbose_name='discount')),
                ('net_vat', models.DecimalField(blank=True, decimal_places=3, max_digits=12, verbose_name='net_vat')),
                ('amount_due', models.DecimalField(blank=True, decimal_places=3, max_digits=12, verbose_name='amount_due')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client')),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.ClientPO')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='company_name')),
                ('contact_person', models.CharField(max_length=200, verbose_name='contact_person')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='mobile_number')),
                ('email_address', models.CharField(max_length=200, verbose_name='email_address')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('supplier_type', models.CharField(choices=[('RM', 'Raw Material'), ('MP', 'Machinery/Parts'), ('I', 'Ink'), ('O', 'Others')], default='not specified', max_length=200, verbose_name='suppier_type')),
                ('department', models.CharField(choices=[('AF', 'Accounting and Finance'), ('HR', 'Human Resource'), ('IT', 'Information Technology'), ('M', 'Marketing'), ('P', 'Purchasing'), ('RD', 'Research and Development'), ('S', 'Sales'), ('O', 'Others')], default='not specified', max_length=200, verbose_name='department')),
            ],
        ),
        migrations.AddField(
            model_name='clientitem',
            name='client_po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.ClientPO'),
        ),
        migrations.AddField(
            model_name='clientitem',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.Product'),
        ),
        migrations.AddField(
            model_name='clientcreditstatus',
            name='invoice_issued',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.SalesInvoice'),
        ),
    ]
