# Generated by Django 2.1.2 on 2018-11-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('laminate', models.IntegerField()),
                ('printed', models.IntegerField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('thickness', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('price_per_piece', models.FloatField()),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green'), ('Violet', 'Violet'), ('Black', 'Black'), ('White', 'White'), ('Plain', 'Plain')], default='Plain', max_length=200, verbose_name='color')),
                ('gusset', models.CharField(choices=[('None', 'None'), ('Side Seal', 'Side Seal'), ('Bottom Seal Double', 'Bottom Seal Double'), ('Big Bottom Seal', 'Big Bottom Seal'), ('Bottom Seal Single', 'Bottom Seal Single')], default='None', max_length=200, verbose_name='gusset')),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.JobOrder')),
            ],
            options={
                'db_table': 'sales_mgt_clientitem',
            },
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment', models.FloatField()),
                ('payment_date', models.DateField()),
                ('old_balance', models.FloatField()),
                ('new_balance', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
            ],
            options={
                'db_table': 'sales_mgt_clientpayment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('material_type', models.CharField(blank=True, choices=[('LLDPE', 'Linear low-density polyethylene'), ('LDPE', 'Low-density polyethylene'), ('HDPE', 'High-density polyethylene'), ('PP', 'Polypropylene'), ('PET', 'Polyethylene terephthalate')], max_length=200, null=True, verbose_name='rm_type')),
                ('products', models.CharField(max_length=300, verbose_name='products')),
                ('prod_price', models.FloatField()),
                ('constant', models.FloatField()),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost_type', models.CharField(max_length=45)),
                ('cost', models.FloatField()),
            ],
            options={
                'db_table': 'sales_mgt_productioncost',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('total_amount', models.FloatField()),
                ('total_amount_computed', models.FloatField(blank=True, null=True)),
                ('amount_due', models.FloatField()),
                ('total_paid', models.FloatField(blank=True, null=True)),
                ('days_passed', models.IntegerField(blank=True, null=True)),
                ('days_overdue', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Late', 'Late'), ('Cancelled', 'Cancelled')], default='Open', max_length=200, verbose_name='status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.JobOrder')),
            ],
            options={
                'db_table': 'sales_mgt_salesinvoice',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('mobile_number', models.CharField(max_length=45)),
                ('email_address', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sales_mgt_supplier',
            },
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesInvoice'),
        ),
        migrations.AddField(
            model_name='clientitem',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Product'),
        ),
    ]
