# Generated by Django 2.1a1 on 2018-06-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCreditStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_status', models.BooleanField(default=True, verbose_name='credit_status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='', max_length=200, verbose_name='note')),
                ('width', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='width')),
                ('length', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='length')),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('O', 'Orange'), ('G', 'Green'), ('V', 'Violet'), ('Blk', 'Black'), ('Wht', 'White'), ('P', 'Plain')], max_length=200, verbose_name='color')),
                ('gusset', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='gusset')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('item_price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='date_issued')),
                ('date_required', models.DateTimeField(auto_now_add=True, verbose_name='date_required')),
                ('terms', models.CharField(max_length=250, verbose_name='terms')),
                ('other_info', models.CharField(max_length=250, verbose_name='other_info')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='total_amount')),
                ('clients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=200, verbose_name='products')),
                ('prod_price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='prod_price')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='clientitem',
            name='client_po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.ClientPO'),
        ),
        migrations.AddField(
            model_name='clientitem',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.Product'),
        ),
    ]
