# Generated by Django 2.1.2 on 2018-11-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientitem',
            name='client_po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.JobOrder'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Product'),
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client'),
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.SalesInvoice'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='client_po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.JobOrder'),
        ),
    ]
