# Generated by Django 2.0.5 on 2018-05-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customerpo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customerpo',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(default=0, max_length=45, verbose_name='contact_number'),
            preserve_default=False,
        ),
    ]
