# Generated by Django 2.1a1 on 2018-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientitem',
            name='note',
        ),
        migrations.AddField(
            model_name='clientpo',
            name='note',
            field=models.CharField(default='', max_length=200, verbose_name='note'),
        ),
    ]
