# Generated by Django 2.1a1 on 2018-06-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0002_auto_20180617_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientpo',
            old_name='clients',
            new_name='client',
        ),
        migrations.AddField(
            model_name='clientpo',
            name='confirmed',
            field=models.BooleanField(default=0, verbose_name='confirmed'),
        ),
        migrations.AddField(
            model_name='clientpo',
            name='laminate',
            field=models.BooleanField(default=0, verbose_name='laminate'),
        ),
    ]
