# Generated by Django 2.1.2 on 2018-11-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20181111_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productioncost',
            options={},
        ),
    ]
