# Generated by Django 2.1.2 on 2018-11-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20181111_1924'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productioncost',
            table=None,
        ),
    ]
