# Generated by Django 2.1a1 on 2018-06-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0003_auto_20180618_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='company_name')),
                ('contact_person', models.CharField(max_length=200, verbose_name='contact_person')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='mobile_number')),
                ('email_address', models.CharField(max_length=200, verbose_name='email_address')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('supplier_type', models.CharField(choices=[('RM', 'Raw Material'), ('MP', 'Machinery/Parts'), ('I', 'Ink'), ('O', 'Others')], default='not specified', max_length=200, verbose_name='suppier_type')),
                ('department', models.CharField(choices=[('AF', 'Accounting and Finance'), ('HR', 'Human Resource'), ('IT', 'Information Technology'), ('M', 'Marketing'), ('P', 'Purchasing'), ('RD', 'Research and Development'), ('S', 'Sales'), ('O', 'Others')], default='not specified', max_length=200, verbose_name='department')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientcreditstatus',
            options={'verbose_name_plural': 'Client credit status'},
        ),
        migrations.RemoveField(
            model_name='clientpo',
            name='laminate',
        ),
        migrations.AddField(
            model_name='clientitem',
            name='laminate',
            field=models.BooleanField(default=0, verbose_name='laminate'),
        ),
    ]
