# Generated by Django 2.0.5 on 2018-06-01 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0002_auto_20180601_1028'),
        ('sales_mgt', '0003_auto_20180531_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCreditStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_status', models.BooleanField(default=True, verbose_name='credit_status')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(verbose_name='date_issued')),
                ('date_required', models.DateField(verbose_name='date_required')),
                ('terms', models.CharField(max_length=250, verbose_name='name')),
                ('other_info', models.CharField(max_length=250, verbose_name='other_info')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='customerpo',
            name='customer_items',
        ),
        migrations.RemoveField(
            model_name='customerpo',
            name='customers',
        ),
        migrations.RenameModel(
            old_name='CustomerItem',
            new_name='ClientItem',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerPO',
        ),
        migrations.AddField(
            model_name='clientpo',
            name='client_items',
            field=models.ManyToManyField(to='sales_mgt.ClientItem'),
        ),
        migrations.AddField(
            model_name='clientpo',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client'),
        ),
    ]
