# Generated by Django 2.1.3 on 2018-11-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20181119_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='days_overdue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
