# Generated by Django 2.1.2 on 2018-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20181111_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='total_amount_computed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='productioncost',
            table='sales_mgt_productioncost',
        ),
    ]
