# Generated by Django 2.0.6 on 2018-06-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0004_auto_20180626_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpo',
            name='terms',
        ),
        migrations.AddField(
            model_name='clientpo',
            name='payment_terms',
            field=models.CharField(choices=[('15', '15 Days'), ('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], default='30 Days', max_length=200, verbose_name='payment terms'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='department',
            field=models.CharField(choices=[('Accounting and Finance', 'Accounting and Finance'), ('Human Resource', 'Human Resource'), ('Information Technology', 'Information Technology'), ('Marketing', 'Marketing'), ('Purchasing', 'Purchasing'), ('Research and Development', 'Research and Development'), ('Sales', 'Sales'), ('Others', 'Others')], default='not specified', max_length=200, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('Raw Material', 'Raw Material'), ('Machinery/Parts', 'Machinery/Parts'), ('Ink', 'Ink'), ('Others', 'Others')], default='not specified', max_length=200, verbose_name='suppier_type'),
        ),
    ]
