# Generated by Django 2.0.5 on 2018-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0004_auto_20180601_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientitem',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='clientpo',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='total_amount'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='gusset',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='gusset'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='length',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='width'),
        ),
    ]
