# Generated by Django 2.1.2 on 2018-11-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20181112_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
    ]
