# Generated by Django 2.0.5 on 2018-06-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0005_auto_20180603_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=200, verbose_name='products')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clientitem',
            name='item_type',
        ),
        migrations.AddField(
            model_name='clientitem',
            name='note',
            field=models.CharField(default='', max_length=200, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='clientitem',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.Product'),
        ),
    ]
