# Generated by Django 2.0.6 on 2018-07-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0006_auto_20180630_1723'),
        ('sales_mgt', '0005_auto_20180628_1603'),
    ]

    operations = [
    ]
