# Generated by Django 2.1a1 on 2018-06-04 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0003_auto_20180603_1451'),
        ('sales_mgt', '0006_auto_20180603_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpo',
            name='client_items',
        ),
        migrations.AddField(
            model_name='clientitem',
            name='client_po',
            field=models.ManyToManyField(to='sales_mgt.ClientPO'),
        ),
        migrations.AddField(
            model_name='clientitem',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client'),
        ),
    ]
