# Generated by Django 2.0.6 on 2018-07-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0006_auto_20180630_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_due', models.DateField(auto_now_add=True, verbose_name='date_due')),
                ('total_paid', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='total_paid')),
                ('balance', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='balance')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientcreditstatus',
            name='credit_status',
        ),
        migrations.RemoveField(
            model_name='clientcreditstatus',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='clientcreditstatus',
            name='invoice_issued',
        ),
        migrations.RemoveField(
            model_name='clientcreditstatus',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='department',
        ),
        migrations.AddField(
            model_name='clientcreditstatus',
            name='status',
            field=models.BooleanField(default=False, verbose_name='laminate'),
        ),
        migrations.AlterField(
            model_name='clientpo',
            name='date_required',
            field=models.DateField(verbose_name='date_required'),
        ),
        migrations.AlterField(
            model_name='clientpo',
            name='other_info',
            field=models.TextField(max_length=250, verbose_name='other_info'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='net_vat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='net_vat'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='credit_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.ClientCreditStatus'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='invoice_issued',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.SalesInvoice'),
        ),
    ]
