# Generated by Django 2.1.2 on 2018-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20181116_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
