# Generated by Django 2.0.6 on 2018-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0007_auto_20180703_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpo',
            name='payment_terms',
            field=models.CharField(choices=[('15', '15 Days'), ('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], default='30', max_length=200, verbose_name='payment terms'),
        ),
    ]
