# Generated by Django 2.1a1 on 2018-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0007_auto_20180604_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpo',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_issued'),
        ),
        migrations.AlterField(
            model_name='clientpo',
            name='date_required',
            field=models.DateTimeField(verbose_name='date_required'),
        ),
    ]
