# Generated by Django 2.1.2 on 2018-11-17 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20181117_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='date_made',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
    ]
