# Generated by Django 2.1a1 on 2018-06-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0008_auto_20180609_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientitem',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='price'),
        ),
    ]
