# Generated by Django 2.1.2 on 2018-11-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_salesinvoice_date_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='days_passed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
