# Generated by Django 2.0.6 on 2018-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0009_auto_20180703_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpo',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved'), ('under production', 'under production'), ('ready for delivery', 'ready for delivery'), ('disapproved', 'disapproved')], default='waiting', max_length=200, verbose_name='status'),
        ),
    ]
