# Generated by Django 2.1a1 on 2018-06-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0010_auto_20180609_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientitem',
            name='client_po',
        ),
        migrations.RemoveField(
            model_name='clientitem',
            name='clients',
        ),
        migrations.AddField(
            model_name='clientpo',
            name='client_item',
            field=models.ManyToManyField(to='sales_mgt.ClientItem'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('O', 'Orange'), ('G', 'Green'), ('V', 'Violet'), ('Blk', 'Black'), ('Wht', 'White'), ('P', 'Plain')], max_length=200, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='clientpo',
            name='terms',
            field=models.CharField(max_length=250, verbose_name='terms'),
        ),
    ]
