# Generated by Django 2.0.6 on 2018-07-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0010_auto_20180704_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Payment_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateField(auto_now_add=True, verbose_name='date_changed')),
                ('client_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.ClientPayment')),
            ],
        ),
        migrations.CreateModel(
            name='PO_Status_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateField(auto_now_add=True, verbose_name='date_changed')),
                ('client_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.ClientPO')),
            ],
        ),
        migrations.AlterField(
            model_name='clientcreditstatus',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
