# Generated by Django 2.1.2 on 2018-11-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesinvoice_days_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
