# Generated by Django 2.0.6 on 2018-07-12 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0011_auto_20180710_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcreditstatus',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client'),
        ),
    ]
