# Generated by Django 2.1.2 on 2018-11-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20181118_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='days_overdue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
