# Generated by Django 2.0.6 on 2018-07-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0004_auto_20180703_1849'),
        ('sales_mgt', '0013_auto_20180712_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client'),
        ),
    ]
