# Generated by Django 2.0.6 on 2018-07-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0014_clientpayment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_payment_history',
            name='client_payment',
        ),
        migrations.DeleteModel(
            name='Client_Payment_History',
        ),
    ]
