# Generated by Django 2.0.6 on 2018-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0016_salesinvoice_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=200, verbose_name='products')),
                ('width', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='width')),
                ('length', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='length')),
                ('gusset', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='gusset')),
                ('prod_price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='prod_price')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='clientitem',
            name='material_type',
            field=models.CharField(choices=[('LDPE', 'Low-density polyethylene'), ('LLDPE', 'Linear low-density polyethylene'), ('HDPE', 'High-density polyethylene'), ('PP', 'Polypropylene'), ('PET', 'Polyethylene terephthalate')], default='LDPE', max_length=200, verbose_name='material_type'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green'), ('Violet', 'Violet'), ('Black', 'Black'), ('White', 'White'), ('Plain', 'Plain')], default='Plain', max_length=200, verbose_name='color'),
        ),
    ]
