# Generated by Django 2.0.6 on 2018-07-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0017_auto_20180712_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpo',
            name='payment_terms',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_terms',
            field=models.CharField(choices=[('15 Days', '15 Days'), ('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], default='30', max_length=200, verbose_name='payment terms'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='gusset',
            field=models.CharField(choices=[('Side Seal', 'Side_Seal'), ('Bottom Seal Double', 'Bottom Seal Double'), ('Big Bottom Seal', 'Side_Seal'), ('Bottome Seal Single', 'Side_Seal')], default='Side Seal', max_length=200, verbose_name='gusset'),
        ),
        migrations.AlterField(
            model_name='preproduct',
            name='gusset',
            field=models.CharField(choices=[('Side Seal', 'Side_Seal'), ('Bottom Seal Double', 'Bottom Seal Double'), ('Big Bottom Seal', 'Side_Seal'), ('Bottome Seal Single', 'Side_Seal')], default='Side Seal', max_length=200, verbose_name='gusset'),
        ),
    ]
