# Generated by Django 2.0.6 on 2018-07-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0018_auto_20180712_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientitem',
            name='gusset',
            field=models.CharField(choices=[('Side Seal', 'Side Seal'), ('Bottom Seal Double', 'Bottom Seal Double'), ('Big Bottom Seal', 'Big Bottom Seal'), ('Bottom Seal Single', 'Bottom Seal Single')], default='Side Seal', max_length=200, verbose_name='gusset'),
        ),
        migrations.AlterField(
            model_name='preproduct',
            name='gusset',
            field=models.CharField(choices=[('Side Seal', 'Side Seal'), ('Bottom Seal Double', 'Bottom Seal Double'), ('Big Bottom Seal', 'Big Bottom Seal'), ('Bottom Seal Single', 'Bottom Seal Single')], default='Side Seal', max_length=200, verbose_name='gusset'),
        ),
    ]
