# Generated by Django 2.0.6 on 2018-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0019_auto_20180712_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_terms',
            field=models.CharField(choices=[('15 Days', '15 Days'), ('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], default='30 Days', max_length=200, verbose_name='payment terms'),
        ),
    ]
