# Generated by Django 2.0.6 on 2018-07-12 09:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0020_auto_20180712_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcreditstatus',
            name='overdue_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='overdue_balance'),
        ),
        migrations.AlterField(
            model_name='clientcreditstatus',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='outstanding_balance'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total_paid'),
        ),
        migrations.AlterField(
            model_name='preproduct',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='preproduct',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='prod_price'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='amount_due'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='net_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='net_vat'),
        ),
    ]
