# Generated by Django 2.0.6 on 2018-07-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0021_auto_20180712_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cancelled',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
