# Generated by Django 2.0.6 on 2018-07-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0023_auto_20180712_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='days_passed',
            field=models.IntegerField(default=0, verbose_name='days_passed'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Late', 'Late'), ('Cancelled', 'Cancelled')], default='Open', max_length=200, verbose_name='status'),
        ),
    ]
