# Generated by Django 2.0.6 on 2018-07-12 13:17

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0024_auto_20180712_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpayment',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='clientpayment',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='clientpayment',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='payment_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, verbose_name='total_paid'),
        ),
    ]
