# Generated by Django 2.0.6 on 2018-07-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0025_auto_20180712_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayment',
            name='payment_date',
            field=models.DateField(blank=True, verbose_name='payment_date'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_issued'),
        ),
    ]
