# Generated by Django 2.0.6 on 2018-07-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0026_auto_20180714_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_status_history',
            name='date_changed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_changed'),
        ),
    ]
