# Generated by Django 2.0.6 on 2018-07-14 14:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0028_auto_20180714_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_type',
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='new_balance'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='old_balance'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(default=1, max_length=200, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(default=1, max_length=200, verbose_name='last_name'),
            preserve_default=False,
        ),
    ]
