# Generated by Django 2.0.6 on 2018-07-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0030_salesinvoice_total_amount_computed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpo',
            name='other_info',
            field=models.TextField(blank=True, max_length=250, verbose_name='other_info'),
        ),
    ]
