# Generated by Django 2.0.6 on 2018-07-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0031_auto_20180715_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='total_amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount_computed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='total_amount_computed'),
        ),
    ]
