# Generated by Django 2.0.6 on 2018-07-17 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0004_auto_20180703_1849'),
        ('sales_mgt', '0033_auto_20180717_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.CharField(choices=[('30 Days', '30 Days'), ('45 Days', '45 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], default='30 Days', max_length=200, verbose_name='payment terms')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='discount')),
                ('net_vat', models.DecimalField(decimal_places=2, default=0.2, max_digits=12, verbose_name='net_vat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_mgt.Client')),
            ],
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='date_due',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_due'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_terms',
            field=models.CharField(choices=[('30 Days', '30 Days'), ('45 Days', '45 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], default='30 Days', max_length=200, verbose_name='payment terms'),
        ),
    ]
