# Generated by Django 2.0.6 on 2018-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0035_remove_clientitem_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(max_length=200, verbose_name='')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cost')),
            ],
        ),
        migrations.AddField(
            model_name='clientitem',
            name='printed',
            field=models.BooleanField(default=True, verbose_name='printed'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='gusset',
            field=models.CharField(choices=[('None', 'None'), ('Side Seal', 'Side Seal'), ('Bottom Seal Double', 'Bottom Seal Double'), ('Big Bottom Seal', 'Big Bottom Seal'), ('Bottom Seal Single', 'Bottom Seal Single')], default='None', max_length=200, verbose_name='gusset'),
        ),
    ]
