# Generated by Django 2.0.6 on 2018-07-18 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0036_auto_20180717_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientitem',
            name='color_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='color_quantity'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='products',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_mgt.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='products',
            field=models.CharField(max_length=300, verbose_name='products'),
        ),
    ]
