# Generated by Django 2.0.6 on 2018-07-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_mgt', '0004_auto_20180703_1849'),
        ('sales_mgt', '0037_auto_20180718_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientConstants',
            new_name='ClientConstant',
        ),
    ]
