# Generated by Django 2.0.6 on 2018-07-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0039_auto_20180718_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total_amount'),
        ),
        migrations.AlterField(
            model_name='productioncost',
            name='cost_type',
            field=models.CharField(max_length=200, verbose_name='cost_type'),
        ),
    ]
