# Generated by Django 2.0.6 on 2018-07-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0041_auto_20180718_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientitem',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='price_per_piece'),
        ),
        migrations.AlterField(
            model_name='clientitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='item_price'),
        ),
    ]
