# Generated by Django 2.1.1 on 2018-09-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_mgt', '0007_merge_20180703_2201'),
        ('sales_mgt', '0042_auto_20180718_1353'),
    ]

    operations = [
    ]
